### ISSUE TITLE
Mplex will freeze reader if stream was closed remotely.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-libp2p#115] opened 2020-03-24 11:58 UTC
This test reproduces a problem.

```nim
import unittest, chronos, tables
import libp2p/[switch,
               multistream,
               protocols/identify,
               connection,
               transports/transport,
               transports/tcptransport,
               multiaddress,
               peerinfo,
               crypto/crypto,
               peer,
               protocols/protocol,
               muxers/muxer,
               muxers/mplex/mplex,
               muxers/mplex/types,
               protocols/secure/secio,
               protocols/secure/secure]

const TestCodec = "/test/proto/1.0.0"
type TestProto = ref object of LPProtocol

proc createSwitch(ma: MultiAddress): (Switch, PeerInfo) =
  var peerInfo: PeerInfo = PeerInfo.init(PrivateKey.random(RSA))
  peerInfo.addrs.add(ma)
  let identify = newIdentify(peerInfo)

  proc createMplex(conn: Connection): Muxer =
    result = newMplex(conn)

  let mplexProvider = newMuxerProvider(createMplex, MplexCodec)
  let transports = @[Transport(newTransport(TcpTransport))]
  let muxers = [(MplexCodec, mplexProvider)].toTable()
  let secureManagers = [(SecioCodec, Secure(newSecio(peerInfo.privateKey)))].toTable()
  let switch = newSwitch(peerInfo,
                         transports,
                         identify,
                         muxers,
                         secureManagers)
  result = (switch, peerInfo)

proc testSwitch(): Future[bool] {.async, gcsafe.} =
  var event = newAsyncEvent()

  proc handle(conn: Connection, proto: string) {.async, gcsafe.} =
    await event.wait()
    event.clear()
    await conn.close()

  let ma1: MultiAddress = Multiaddress.init("/ip4/0.0.0.0/tcp/0")
  let ma2: MultiAddress = Multiaddress.init("/ip4/0.0.0.0/tcp/0")

  var peerInfo1, peerInfo2: PeerInfo
  var switch1, switch2: Switch
  var awaiters: seq[Future[void]]

  (switch1, peerInfo1) = createSwitch(ma1)

  let testProto = new TestProto
  testProto.codec = TestCodec
  testProto.handler = handle
  switch1.mount(testProto)

  (switch2, peerInfo2) = createSwitch(ma2)
  awaiters.add(await switch1.start())
  awaiters.add(await switch2.start())
  await switch2.connect(switch1.peerInfo)

  let conn = await switch2.dial(switch1.peerInfo, TestCodec)
  let msgfut = conn.readLp()
  event.fire()
  var res = await withTimeout(msgfut, 1.seconds)

  await allFutures(switch1.stop(), switch2.stop())
  await allFutures(awaiters)

  result = res

when isMainModule:
  suite "Mplex tests":
    test "Mplex freeze after stream get closed remotely test":
      check waitFor(testSwitch()) == true
```

**Comment by dryajov** [comment] 2020-03-24 21:58
This actually works as expected, you can't do a `conn.readLp()` without writing anything in the handler, it will hang as it is expected, because `readLp` is expecting input data to arrive.

There is another issue however, for some reason closing the connection in the handler now throws an `EOF`, this used to work

**Comment by dryajov** [comment] 2020-03-24 22:26
Actually, there is no issue with closing the connection either, it was a local change that was causing this.

**Comment by dryajov** [comment] 2020-03-24 22:28
For reference, this is the modified snippet that works:

```nim
import unittest, chronos, tables
import libp2p/[switch,
               multistream,
               protocols/identify,
               connection,
               transports/transport,
               transports/tcptransport,
               multiaddress,
               peerinfo,
               crypto/crypto,
               peer,
               protocols/protocol,
               muxers/muxer,
               muxers/mplex/mplex,
               muxers/mplex/types,
               protocols/secure/secio,
               protocols/secure/secure]

const TestCodec = "/test/proto/1.0.0"
type TestProto = ref object of LPProtocol

proc createSwitch(ma: MultiAddress): (Switch, PeerInfo) =
  var peerInfo: PeerInfo = PeerInfo.init(PrivateKey.random(RSA))
  peerInfo.addrs.add(ma)
  let identify = newIdentify(peerInfo)

  proc createMplex(conn: Connection): Muxer =
    result = newMplex(conn)

  let mplexProvider = newMuxerProvider(createMplex, MplexCodec)
  let transports = @[Transport(newTransport(TcpTransport))]
  let muxers = [(MplexCodec, mplexProvider)].toTable()
  let secureManagers = [(SecioCodec, Secure(newSecio(peerInfo.privateKey)))].toTable()
  let switch = newSwitch(peerInfo,
                         transports,
                         identify,
                         muxers,
                         secureManagers)
  result = (switch, peerInfo)

proc testSwitch(): Future[bool] {.async, gcsafe.} =
  var event = newAsyncEvent()

  proc handle(conn: Connection, proto: string) {.async, gcsafe.} =
    await event.wait()
    event.clear()
    await conn.writeLp("Hello")
    await conn.close()

  let ma1: MultiAddress = Multiaddress.init("/ip4/0.0.0.0/tcp/0")
  let ma2: MultiAddress = Multiaddress.init("/ip4/0.0.0.0/tcp/0")

  var peerInfo1, peerInfo2: PeerInfo
  var switch1, switch2: Switch
  var awaiters: seq[Future[void]]

  (switch1, peerInfo1) = createSwitch(ma1)

  let testProto = new TestProto
  testProto.codec = TestCodec
  testProto.handler = handle
  switch1.mount(testProto)

  (switch2, peerInfo2) = createSwitch(ma2)
  awaiters.add(await switch1.start())
  awaiters.add(await switch2.start())
  await switch2.connect(switch1.peerInfo)

  let conn = await switch2.dial(switch1.peerInfo, TestCodec)
  let msgfut = conn.readLp()
  event.fire()
  var res = await withTimeout(msgfut, 1.seconds)

  await allFutures(switch1.stop(), switch2.stop())
  await allFutures(awaiters)

  result = res

when isMainModule:
  suite "Mplex tests":
    test "Mplex freeze after stream get closed remotely test":
      check waitFor(testSwitch()) == true
```

**Comment by arnetheduck** [comment] 2020-03-25 07:56
the handler closes the stream, shouldn't `readLp` fail/abort in that case?

**Comment by cheatfate** [comment] 2020-03-25 09:44
This test case shows that if there is pending `read` operation present and remote peer closes stream, this `read` operation will never be awakened and will freeze forever. So this is exactly bug.

**Comment by cheatfate** [comment] 2020-03-25 09:46
`read` in such case should raise `EOF` exception or return `0` bytes, but right now it just blocks forever.

**Comment by dryajov** [comment] 2020-03-25 14:51
Ok , that does sound like a bug and I think I know where the issue is, the problem is that I haven't yet figured out a good place to cleanup channels properly. I'll be looking into it now.

**Closed** 2020-03-28 15:29 UTC
