### ISSUE TITLE
Channel leak on cancellation

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#393] opened 2020-10-07 12:04 UTC
Using the following script, it's possible to find channels that have not been closed properly - in particular, they are correlated with request timeouts triggered from here: https://github.com/status-im/nim-beacon-chain/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/eth2_network.nim#L647

ie when running the script and looking for logs surrounding the leaking channels, that line pops up - what happens with a timeout is that `readChunkPayload` gets cancelled by the timer.

```python
import re,sys

re0 = re.compile(r"Creating.*channel\":\"([^\:]+:.*?)[:\"]")
re1 = re.compile(r"Closed.*s\":\"([^\"]+)")

x = set()

with open(sys.argv[1]) as f:
  data = f.readlines()
for line in data:
  for match in re0.finditer(line):
      x.add(match.group(1))

  for match in re1.finditer(line):
    x.discard(match.group(1))

for a in x:
  for line in data:
    if a in line:
      print(line, end = '')      
  print(a)
```

**Comment by sinkingsugar** [comment] 2020-10-09 05:07
I'm digging this a bit, `readChunkPayload` possible fault points, or anyway cancellation points, are a `readVarint` or, if the `readVarint` succeedes, a `readExactly`; both on a `LPStream`.
In turn they all use `readOnce`, which in this case assuming mplex it's a `LPChannel`.
`LPChannel.readOnce` does NOT handle cancellation but handles `CatchableError` alone.. this is probably a issue.

**Comment by sinkingsugar** [comment] 2020-10-09 05:22
@arnetheduck I'm a bit confused on the Open/Close stream tho, `readChunkPayload` seems to use an always opened connection to me, from `handleIncomingStream`, altho I might be confused by the amount of templates.

**Comment by arnetheduck** [comment] 2020-10-09 06:49
The message I referred to in the bug description is printed when this happens - @zah understands the eth2 flow best though - I believe it should be possible to write a smaller test case here though

**Comment by zah** [comment] 2020-10-14 14:37
The code linked by Jacek is executed only on incoming connections indeed. I can try replicating the issue locally with a custom request client that doesn't send data in time. Doing this in a loop will hopefully confirm the leak.

**Comment by arnetheduck** [comment] 2020-10-14 15:20
@zah libp2p now monitors timeouts per connection (https://github.com/status-im/nim-libp2p/blob/556213abf4bcfb33e27d28e5148619343df05dbb/libp2p/stream/connection.nim#L33) - we should probably set that to the request timeout for these channels - that will cause them to be reset which will wake up `readOnce` like this timeout would without encumbering chronos with yet another timer+future wrapper (timers are expensive) - that's also a better place to handle channel timeouts in general because not all channels are available to NBC so libp2p _has_ to have activity timeouts built in.

**Comment by dryajov** [comment] 2020-10-14 15:26
If that's the route we wanna go, we can use the `inTimeout` and `outTimeout` params in standard setup - https://github.com/status-im/nim-libp2p/blob/556213abf4/libp2p/standard_setup.nim#L29-L30. This allow controlling channel activity depending on the connection's direction.

**Comment by zah** [comment] 2020-10-14 15:58
"time to fist byte" is defined to 5 seconds in the networking spec. It's not reasonable to set a global policy with such a timeout across all channels, but perhaps you can come up with a solution that is defined per-protocol.

**Comment by dryajov** [comment] 2020-10-23 01:02
So it appears that the issue is related  half closed channels. 

What seems to happen is:

- A close is issues and the close message is sent - https://github.com/status-im/nim-libp2p/blob/master/libp2p/muxers/mplex/lpchannel.nim#L131
- If the channel is already EOFed the underlying `LPStream.close()` is called in https://github.com/status-im/nim-libp2p/blob/master/libp2p/muxers/mplex/lpchannel.nim#L139
- If the channel isn't yet EOFed underlying `LPStream.close()` will be skipped and will only trigger once an EOF is received from the remote
- If the underlying `LPStream.close()` isn't called, the channel will leak because it's close event isn't triggered and the channel is never released, this is also reflected in the channel counts, since these are adjusted in the base `LPStream.close`
- This can happen in any of the following scenarios
  - If the `close` is canceled or an exception is raised the close sequence won't complete
  - If sending the close message hangs/doesn't complete the close sequence won't complete 
  - If the remote never sends the EOF, the close sequence won't complete
- In all of the above cases, the channel needs to be reset to complete the close sequence

**Comment by arnetheduck** [comment] 2020-10-23 06:05
This does not correspond to the observed behaviour though: the timeout timer should reset the connection after a few few minutes in this case since there's no more activity (no reading and no writing) - the leak is permanent however, and the number of open channels keeps growing.

**Comment by dryajov** [comment] 2021-02-02 15:08
We have fixed most issues related to channel leaks and cancellations, however, we need to increase our overall cancelation coverage. Leaving this issue open for now for reference even tho it doesn't appear to be present anymore.

**Comment by Menduist** [comment] 2022-01-04 13:20
Closing inf favor of #137

**Closed by Menduist** 2022-01-04 13:20 UTC
Labels: v1
